[plugins]
shadow = { id = "com.gradleup.shadow", version = "9.0.0" }
lombok = { id = "io.freefair.lombok", version = "8.14.2" }

[libraries]
mysql = { group = "mysql", name = "mysql-connector-java", version = "8.0.33"}
hikaricp = { group = "com.zaxxer", name = "HikariCP", version = "5.1.0"}
jetanno = { group = "org.jetbrains", name = "annotations", version = "24.0.1"}

[bundles]
database = ["mysql", "hikaricp"]